# Production configuration
environment: production
debug: false

database:
  url: ${DATABASE_URL}
  pool_size: 20
  max_overflow: 30

redis:
  url: ${REDIS_URL}

security:
  secret_key: ${SECRET_KEY}
  algorithm: HS256
  access_token_expire_minutes: 30

rate_limits:
  lookup_per_hour: 2
  batch_lookup_per_day: 5
  api_requests_per_minute: 60

agents:
  timeout: 30
  max_retries: 3
  confidence_threshold: 0.85
