name: Auto-fix Code Issues

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-fix:
    name: Auto-fix Python Code
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: ${{ github.head_ref }}
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    
    - name: Install Ruff
      run: |
        python -m pip install --upgrade pip
        pip install ruff black isort
    
    - name: Auto-fix with Ruff
      run: |
        ruff check --fix .
        ruff format .
      continue-on-error: true
    
    - name: Auto-format with Black
      run: |
        black .
      continue-on-error: true
    
    - name: Auto-sort imports with isort
      run: |
        isort .
      continue-on-error: true
    
    - name: Check for changes
      id: verify_diff
      run: |
        git diff --quiet . || echo "changed=true" >> $GITHUB_OUTPUT
    
    - name: Commit and push fixes
      if: steps.verify_diff.outputs.changed == 'true'
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "style: auto-fix code issues [skip ci]"
        git push
